version: '3.8'

services:
  bipper_client:
    build:
      context: ..
      dockerfile: docker/client.dockerfile
    environment:
      - FLASK_PORT=5002
      - FLASK_SECRET=7E*2aJ^e4rGuuH%c
    network_mode: host
    volumes:
      - ./log:/log

  bipper_server:
    build:
      context: ..
      dockerfile: docker/server.dockerfile
    network_mode: host
    depends_on:
      - bipper_db
    volumes:
      - ./log:/log

  bipper_db:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=bipper
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bipper_db
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data