version: '3.8'

services:
  bipper_db_test:
    image: postgres:alpine
    ports:
      - 9002:5432
    restart: always
    environment:
      - POSTGRES_USER=bipper
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bipper_db
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data