INSERT INTO locations (location_district, location_county, location_zone)
VALUES ('Lisboa', 'Lisboa', 'Alvalade'),
       ('Lisboa', 'Lisboa', 'Parque das Nações'),
       ('Lisboa', 'Lisboa', 'Penha de França'),
       ('Lisboa', 'Lisboa', 'Santa Clara'),
       ('Lisboa', 'Lisboa', 'Santa Maria Maior'),
       ('Lisboa', 'Lisboa', 'São Domingues de Benfica'),
       ('Lisboa', 'Lisboa', 'Ajuda'),
       ('Lisboa', 'Lisboa', 'Arroios'),
       ('Lisboa', 'Lisboa', 'Avenidas Novas'),
       ('Lisboa', 'Lisboa', 'Beato'),
       ('Lisboa', 'Lisboa', 'Belém'),
       ('Lisboa', 'Lisboa', 'Areeiro'),
       ('Lisboa', 'Lisboa', 'Benfica'),
       ('Lisboa', 'Lisboa', 'Campo de Ourique'),
       ('Lisboa', 'Lisboa', 'Alcântara'),
       ('Lisboa', 'Lisboa', 'Campolide'),
       ('Lisboa', 'Lisboa', 'Carnide'),
       ('Lisboa', 'Lisboa', 'Misericórdia'),
       ('Lisboa', 'Lisboa', 'Estrela'),
       ('Lisboa', 'Lisboa', 'Santo António'),
       ('Lisboa', 'Lisboa', 'Lumiar'),
       ('Lisboa', 'Lisboa', 'Marvila'),
       ('Lisboa', 'Lisboa', 'Olivais'),
       ('Lisboa', 'Lisboa', 'São Vicente'),

       ('Lisboa', 'Torres Vedras', 'Freiria'),
       ('Lisboa', 'Torres Vedras', 'Ponte do Rol'),
       ('Lisboa', 'Torres Vedras', 'Ramalhal'),
       ('Lisboa', 'Torres Vedras', 'São Pedro da Cadeira'),
       ('Lisboa', 'Torres Vedras', 'Silveira'),
       ('Lisboa', 'Torres Vedras', 'Turcifal'),
       ('Lisboa', 'Torres Vedras', 'Ventosa'),
       ('Lisboa', 'Torres Vedras', 'A dos Cunhados e Maceira'),
       ('Lisboa', 'Torres Vedras', 'Campelos e Outeiro da Cabeça'),
       ('Lisboa', 'Torres Vedras', 'Carvoeira e Carmões'),
       ('Lisboa', 'Torres Vedras', 'Dois Portos e Runa'),
       ('Lisboa', 'Torres Vedras', 'Maxial e Monte Redondo'),
       ('Lisboa', 'Torres Vedras', 'Santa Maria, São Pedro e Matacães'),

       ('Porto', 'Porto', 'Bonfim'),
       ('Porto', 'Porto', 'Campanhã'),
       ('Porto', 'Porto', 'Paranhos'),
       ('Porto', 'Porto', 'Ramalde'),
       ('Porto', 'Porto', 'Aldoar, Foz do Douro e Nevogilde'),
       ('Porto', 'Porto', 'Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória'),
       ('Porto', 'Porto', 'Lordelo do Ouro e Massarelos');
